notifications:
  email: false
git:
  quiet: true
  depth: false
language: node
node_js: lts/*
python: 3.7
service: docker
os: linux
addons:
  apt:
    update: true
    packages:
      - curl
      - sudo
      - lsof
      - docker-ce
      - python3-pip
install: true
before_install:
  - export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 3000 5000 8080 5432
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
jobs:
  include:
    - stage: test
      name: test
      before_script:
        - cd $TRAVIS_BUILD_DIR && npm i
        - cd $TRAVIS_BUILD_DIR && npm run build
        - cd $TRAVIS_BUILD_DIR && docker run -d --rm --name app -p 80:80 -v `pwd`/dist:/usr/share/nginx/html:ro
                                                                  --health-cmd="wget -q --spider http://127.0.0.1:80/ || exit 1"
                                                                  --health-start-period=1s
                                                                  --health-interval=1s
                                                                  --health-retries=33
                                                                  --health-timeout=1s
                                                                  nginx:1.17.6-alpine
        - wait_healthy_docker_containers 1
      script:
        - http :/
      after_script: docker rm -f -v app
    - stage: deploy
      name: GitHub pages deploy
      script: skip
      jdk: openjdk8
      before_deploy:
        - cd $TRAVIS_BUILD_DIR && npm i
        - cd $TRAVIS_BUILD_DIR && npm run predeploy
      env:
        - secure: "L1rYF9uJjBNbAz4ZHlP8iu2AuIESACxjTur6bYGGPHPQ1TvYJxgEz5owpFvKjBy2gpnahJ/tlNm/kwnPEVy5DTY+XUfLTEhyfE4l0QuSjsS8Aae/smBcU7UO8FnAHQyGTx6ATxRQvsIsPQAI8Hl28s/jolvAqx5bK0qvYC+tkJ9TjlBZH+3oyMxiz2BNdobAWp0uLybtV/7jq/4v8qvspqzhhNpGJsU1zi3MNFPQHYWKTOfOLTYOAJIkgMuvh60Is9TSDiJUI0Mkcf7pEGRQiD0MLj3gx5pcn3NaZvCLRZ2DrxNY5LclGT4bM1rKdk9vTY7kJfHUZMcMjmbyK7Qe5pXEXV1asv/TLssz6eVZngmob/80ogjE6b3PWfK3gXhpNLvE2zkY+gNKdaF14IHrasL5EAMJWI4DWgjINFhNZr6GyyALLkoJlo8NC5D4N48rRanh/nicPyYaxDJ4NUZslYQiZWgfZh9BijODc2nB+8vPPlNU9suYOm8cH+fIuiSxIV9vx7iuSH8uaRF3iMEXgmo2x5+l1Ff1KRDWZKp/Z0GGSIsiEClNcneN1z4OtYU7XKMFIyuLi6yLN5WIBXAUodJofDDvEjLKCvhMhETlKwMMK8zlsdId7SzdbscyoisYqQSek3nka+RNIRwt6E+w5c6lbSzGTI1Em2M7+5uLfO8="
      deploy: &pages
        provider: pages
        skip-cleanup: true
        keep-history: true
        target_branch: gh-pages
        # travis encrypt GITHUB_TOKEN=<your github repo token> --add
        github-token: "$GITHUB_TOKEN"
        local-dir: $TRAVIS_BUILD_DIR/dist
        on:
          branch: master
cache:
  directories:
  - ~/.m2
  - ~/.n*
  - node_modules
  - ~/.local/daggerok
